apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: vue001dep 
spec:

  selector:
    matchLabels:
      app: vue001kube 

  template: 

    metadata:
      labels:
        app: vue001kube 

    # 파드 하나의 스펙
    spec:
      containers:
      - name: vue-container 
        image: null00007/vue:latest 
        imagePullPolicy: Always 
        ports:
        - containerPort: 5173
